### ISSUE TITLE
No separators displayed

### ISSUE THREAD

**Issue by energiebrand** [florindumitrescu94/DashBoard_PowerBox_V2#3]
I have the problem that under N.I.N.A. (ASCOM) unfortunately no separators are displayed in the measured values. For example, if the temperature is 23.45°C, then in N.I.N.A "2345" will be displayed. Could this be due to the ASCOM driver? Here in Germany (possibly all of Europe) a comma is expected as a separator, not a period. Is this where the problem lies?

**Comment by florindumitrescu94** [comment]
Hello! It could be that.. I am in Europe too, but I've always been using US
settings on my computer, so I've never faced this issue.

Thing is, there is no setting in the ASCOM driver that I know of that sets
the decimal separator. Also, the values in the arduino also have a dot as a
decimal separator.

I tried changing my settings to use a comma as a decimal separator, but
NINA seems to be using a dot as a decimal separator, anyways, so I suspect
it is forcing the decimal separator to always be "." in its' code. When I
tried starting the powerbox driver with the Region settings set to Germany,
I got the same result as you (no separators).

I guess there is a way to avoid this issue by forcing the decimal separator
to always be "." in the driver, as well. I will add the necessary code to
the driver, but I am currently away on vacation and I'll be back beginning
of August. I'll let you know when I release the solution.

**Comment by energiebrand** [comment]
Meanwhile I found the problem in the Windows settings. I had to change the settings from "," to ".". Hope that will have no negative influence on anything in N.I.N.A. :-)

**Comment by florindumitrescu94** [comment]
Glad to hear it worked for you! Yeah, NINA seems to be happy with "." as decimal separator. I will include a fix for this in my driver to avoid this in the future. Thanks a bunch for raising this issue!

**Comment by energiebrand** [comment]
Yes, it would be nice if the user will be able to select the separator in the ASCON-configuration window maybe. Changing it globally in WIN is not a good solution. Don't know if it will be possible. Maybe you should add  a hint in your description if someone runs into the trap.
